common: &common
  working_directory: ~/dockerfile-ci
  docker:
    - image: alpine:3.7
  environment:
    COVALENCE_VERSION: 0.8.2
    DOCKER_IMAGE: 'unifio/covalence'
    TERRAFORM_VERSION: 0.10.6

version: 2
jobs:
  build_covalence:
    <<: *common
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Install dependencies
          command: |
            docker info
            if [[ -e ~/docker/image.tar ]]; then docker load --input ~/docker/image.tar; fi
            docker build --rm=false --build-arg GEMFURY_SOURCE_URL_TOKEN=$GEMFURY_SOURCE_URL_TOKEN -t ${DOCKER_IMAGE} .
            mkdir -p ~/docker
            docker save ${DOCKER_IMAGE} > ~/docker/image.tar

      - run:
          name: Execute acceptance test
          command: |
            docker run -v /home/ubuntu/.aws:/root/.aws \
                 -v /home/ubuntu/dockerfile-covalence/uat:/home/ubuntu/dockerfile-covalence/uat \
                 -w /home/ubuntu/dockerfile-covalence/uat \
                 -e COVALENCE_TEST_ENVS=uat \
                 --entrypoint=/bin/sh \
                 ${DOCKER_IMAGE} -c "
                 apk add --no-cache --update unzip && \
                 wget -q \"https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip\" && \
                 unzip -d /usr/local/bin terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
                 rake ci && \
                 rake uat:apply && \
                 rake uat:destroy"

      - deploy:
          name: Register Covalence image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker tag -f `docker images | grep -E "${DOCKER_IMAGE}" | awk '{print $3}'` ${DOCKER_IMAGE}:${COVALENCE_VERSION}
              docker push ${DOCKER_IMAGE}
            fi

workflows:
  version: 2
  ci_container_pipeline:
    jobs:
      - build_covalence
